import { Injectable, Logger } from '@nestjs/common';
import { PrismaService } from '../../database/prisma/prisma.service';
import { ConfigService } from '@nestjs/config';
import { SafetyTier, RiskLevel } from '@prisma/client';

const GROUNDING_FLOWS = {
  '5-4-3-2-1': {
    name: '5-4-3-2-1 Grounding',
    description: 'Sensory awareness to anchor you in the present moment',
    steps: [
      { order: 1, prompt: 'Look around you. Name **5 things you can see** right now.', durationSecs: 30 },
      { order: 2, prompt: 'Now notice **4 things you can touch** — feel their texture.', durationSecs: 25 },
      { order: 3, prompt: 'Listen carefully. What are **3 things you can hear**?', durationSecs: 20 },
      { order: 4, prompt: 'Notice **2 things you can smell** — or imagine a scent that feels safe.', durationSecs: 15 },
      { order: 5, prompt: 'Finally, notice **1 thing you can taste**. Take a slow breath.', durationSecs: 15 },
    ],
  },
  'box-breathing': {
    name: 'Box Breathing',
    description: 'Regulated breathing to calm your nervous system',
    steps: [
      { order: 1, prompt: 'Breathe **IN** slowly for 4 counts: 1... 2... 3... 4...', durationSecs: 4 },
      { order: 2, prompt: '**HOLD** your breath for 4 counts: 1... 2... 3... 4...', durationSecs: 4 },
      { order: 3, prompt: 'Breathe **OUT** slowly for 4 counts: 1... 2... 3... 4...', durationSecs: 4 },
      { order: 4, prompt: '**HOLD** empty for 4 counts: 1... 2... 3... 4...', durationSecs: 4 },
      { order: 5, prompt: 'Repeat this cycle. You are safe. Each breath brings calm.', durationSecs: 6 },
    ],
  },
  'safe-place': {
    name: 'Safe Place Visualization',
    description: 'A mental sanctuary when everything feels overwhelming',
    steps: [
      { order: 1, prompt: 'Close your eyes if that feels safe. Take three slow breaths.', durationSecs: 20 },
      { order: 2, prompt: 'Picture a place — real or imagined — where you feel completely safe and at ease.', durationSecs: 25 },
      { order: 3, prompt: 'Notice the details of this place. What do you see? What sounds are there?', durationSecs: 30 },
      { order: 4, prompt: 'Feel the ground beneath you. Feel the temperature. You are safe here.', durationSecs: 25 },
      { order: 5, prompt: 'Breathe this place in. You can return here anytime you need to.', durationSecs: 20 },
    ],
  },
  'cold-water': {
    name: 'Cold Water Reset',
    description: 'A physical reset to interrupt an emotional spiral',
    steps: [
      { order: 1, prompt: 'If possible, go to a sink or get a cold drink. Cold water helps regulate your nervous system.', durationSecs: 15 },
      { order: 2, prompt: 'Splash cold water on your face, or hold cold water in your hands. Feel it.', durationSecs: 20 },
      { order: 3, prompt: 'Or hold an ice cube, or put your wrists under cold water for 30 seconds.', durationSecs: 30 },
      { order: 4, prompt: 'Notice the physical sensation. Your body is responding. You are present.', durationSecs: 15 },
      { order: 5, prompt: 'Take a slow breath. The intensity is passing. You are okay.', durationSecs: 15 },
    ],
  },
} as const;

const CRISIS_RESOURCES = [
  { name: '988 Suicide & Crisis Lifeline', contact: 'Call or text 988', available: '24/7', country: 'US' },
  { name: 'Crisis Text Line', contact: 'Text HOME to 741741', available: '24/7', country: 'US' },
  { name: 'IASP Crisis Centres', contact: 'https://www.iasp.info/resources/Crisis_Centres/', available: '24/7', country: 'International' },
  { name: 'Emergency Services', contact: '911 (US) or local emergency number', available: '24/7', country: 'Varies' },
];

@Injectable()
export class PanicService {
  private readonly logger = new Logger(PanicService.name);
  private readonly webhookUrl?: string;

  constructor(
    private readonly prisma: PrismaService,
    private readonly config: ConfigService,
  ) {
    this.webhookUrl = this.config.get<string>('safety.webhookUrl');
  }

  getAvailableFlows() {
    return Object.entries(GROUNDING_FLOWS).map(([key, flow]) => ({
      key,
      name: flow.name,
      description: flow.description,
      stepCount: flow.steps.length,
      estimatedMinutes: Math.ceil(flow.steps.reduce((s, step) => s + step.durationSecs, 0) / 60),
    }));
  }

  getFlow(key: keyof typeof GROUNDING_FLOWS) {
    const flow = GROUNDING_FLOWS[key];
    if (!flow) return null;
    return { key, ...flow };
  }

  getCrisisResources() {
    return CRISIS_RESOURCES;
  }

  async triggerPanicMode(userId: string, organizationId: string, signal: string) {
    const riskAssessment = await this.prisma.riskAssessment.create({
      data: {
        userId,
        organizationId,
        level: RiskLevel.HIGH,
        safetyTier: SafetyTier.ELEVATED,
        signals: [signal],
        sourceType: 'PANIC_BUTTON',
        autoGenerated: true,
      },
    });

    await this.prisma.safetyFlag.create({
      data: {
        userId,
        organizationId,
        tier: SafetyTier.ELEVATED,
        signals: [signal],
        sourceType: 'PANIC_BUTTON',
        sourceId: riskAssessment.id,
      },
    });

    void this.fireWebhook(userId, organizationId, signal);

    return {
      riskAssessmentId: riskAssessment.id,
      resources: CRISIS_RESOURCES,
      recommendedFlow: GROUNDING_FLOWS['5-4-3-2-1'],
      message: "I'm right here with you. You are not alone. Let's take this one step at a time.",
    };
  }

  async startGroundingSession(userId: string, organizationId: string, flowKey: string) {
    const flow = GROUNDING_FLOWS[flowKey as keyof typeof GROUNDING_FLOWS];
    if (!flow) return null;

    const session = await this.prisma.safetyFlag.create({
      data: {
        userId,
        organizationId,
        tier: SafetyTier.DISTRESS,
        signals: [`grounding_session:${flowKey}`],
        sourceType: 'GROUNDING_SESSION',
      },
    });

    return {
      sessionId: session.id,
      flow: { key: flowKey, ...flow },
      startedAt: new Date().toISOString(),
    };
  }

  async completeGroundingSession(sessionId: string, userId: string, completedSteps: number, feelingAfter?: number) {
    await this.prisma.safetyFlag.update({
      where: { id: sessionId },
      data: { resolved: true, resolvedAt: new Date() },
    });

    return {
      completed: true,
      stepsCompleted: completedSteps,
      feelingAfter,
      message: completedSteps >= 3
        ? 'You did something really brave by working through that. Take your time.'
        : 'Even starting this takes courage. You can try again whenever you are ready.',
    };
  }

  async checkInAfterCrisis(userId: string, organizationId: string, safeNow: boolean, notes?: string) {
    await this.prisma.safetyFlag.create({
      data: {
        userId,
        organizationId,
        tier: safeNow ? SafetyTier.NONE : SafetyTier.DISTRESS,
        signals: safeNow ? ['post_crisis_safe'] : ['post_crisis_still_distressed'],
        sourceType: 'CRISIS_CHECKIN',
        resolved: safeNow,
        resolvedAt: safeNow ? new Date() : undefined,
      },
    });

    if (!safeNow) {
      void this.fireWebhook(userId, organizationId, 'post_crisis_still_distressed');
    }

    return {
      safeNow,
      resources: safeNow ? [] : CRISIS_RESOURCES,
      message: safeNow
        ? "I'm so glad you're feeling safer. You handled something really hard today."
        : "Please reach out to a crisis line right now — they are there for exactly this. You deserve real support.",
    };
  }

  async getSafetyHistory(userId: string, organizationId: string) {
    return this.prisma.safetyFlag.findMany({
      where: { userId, organizationId },
      orderBy: { createdAt: 'desc' },
      take: 20,
    });
  }

  private async fireWebhook(userId: string, organizationId: string, signal: string) {
    if (!this.webhookUrl) return;
    try {
      await fetch(this.webhookUrl, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          event: 'PANIC_MODE_TRIGGERED',
          organizationId,
          signal,
          timestamp: new Date().toISOString(),
        }),
      });
    } catch (err) {
      this.logger.error('Safety webhook failed', err);
    }
  }
}
